##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.11.2] date: [Wed Mar 10 20:38:30 EST 2021]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = GD32VF103C_xxSPL


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = .build

######################################
# source
######################################
# C sources
C_SOURCES =  \
 .//drivers/RISCV/stubs/fstat.c \
 .//drivers/RISCV/stubs/read.c \
 .//drivers/RISCV/stubs/write_hex.c \
 .//drivers/RISCV/stubs/_exit.c \
 .//drivers/RISCV/stubs/lseek.c \
 .//drivers/RISCV/stubs/isatty.c \
 .//drivers/RISCV/stubs/sbrk.c \
 .//drivers/RISCV/stubs/write.c \
 .//drivers/RISCV/stubs/close.c \
 .//drivers/RISCV/drivers/n200_func.c \
 .//drivers/RISCV/env_Eclipse/your_printf.c \
 .//drivers/RISCV/env_Eclipse/init.c \
 .//drivers/RISCV/env_Eclipse/handlers.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_dac.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_fwdgt.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_dma.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_eclic.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_adc.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_crc.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_exti.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_timer.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_exmc.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_can.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_bkp.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_fmc.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_pmu.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_spi.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_rtc.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_usart.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_wwdgt.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_i2c.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_gpio.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_rcu.c \
 .//drivers/GD32VF103_standard_peripheral/Source/gd32vf103_dbg.c \
 .//drivers/GD32VF103_standard_peripheral/system_gd32vf103.c \
 .//rt-thread/board.c \
 .//rt-thread/libcpu/risc-v/common/cpuport.c \
 .//rt-thread/src/thread.c \
 .//rt-thread/src/components.c \
 .//rt-thread/src/slab.c \
 .//rt-thread/src/timer.c \
 .//rt-thread/src/object.c \
 .//rt-thread/src/irq.c \
 .//rt-thread/src/cpu.c \
 .//rt-thread/src/kservice.c \
 .//rt-thread/src/mem.c \
 .//rt-thread/src/mempool.c \
 .//rt-thread/src/clock.c \
 .//rt-thread/src/memheap.c \
 .//rt-thread/src/ipc.c \
 .//rt-thread/src/scheduler.c \
 .//rt-thread/src/idle.c \
 .//src/main.c

 
# ASM sources
ASM_SOURCES =  \
drivers/RISCV/env_Eclipse/entry.S \
drivers/RISCV/env_Eclipse/start.S \
rt-thread/libcpu/risc-v/bumblebee/interrupt_gcc.S \
rt-thread/libcpu/risc-v/common/context_gcc.S

#######################################
# binaries
#######################################
PREFIX = riscv-nuclei-elf-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -march=rv32imac -mabi=ilp32 -mcmodel=medlow

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DHXTAL_VALUE=8000000 \
-D__GD32VF103C_START__


# AS includes
AS_INCLUDES = \
-Idrivers/RISCV/drivers

# C includes
C_INCLUDES =  \
-Iinc \
-Idrivers/GD32VF103_standard_peripheral/ \
-Idrivers/GD32VF103_standard_peripheral/Include \
-Idrivers/RISCV/drivers \
-Idrivers/RISCV/stubs \
-Irt-thread/include \
-Irt-thread/include/libc \
-Irt-thread/libcpu/risc-v/common \
-Irt-thread


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -fno-common -fsigned-char -fmessage-length=0 -std=gnu11

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -fno-common -fsigned-char -fmessage-length=0 -std=gnu11

ifeq ($(DEBUG), 1)
CFLAGS += -g -Og
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

# Generate map file
CFLAGS += -Wl,-Map,${TARGET}.map

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = drivers/RISCV/env_Eclipse/GD32VF103xB.lds

# libraries
LIBS = -lc
LIBDIR = 
LDFLAGS = $(MCU) -nostartfiles -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
